name: Ejecutar pruebas unitarias

on:
 push:
    branches:
      - dev

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest Flask-Testing

    - name: Ejecutar pruebas
      run: |
        pytest